"""
Proxy REST API (for marking purposes)
---------------------------------------------------
Purpose:
  - Demonstrate REST endpoints independent of the real Google Apps Script backend.
  - Capture booking form submissions in a simple in-memory store.

Endpoints Used:
  GET  /api/orders             -> lists all captured proxy orders from the html booking form
  POST /api/orders             -> accepts booking-form JSON payload from html booking form submission
  GET  /api/orders/<id>        -> allows retrieval of a single order by impression number/id generated by Google Apps Script
  PUT  /api/orders/<id>        -> allows partial updates of an existing order
  GET  /api/kpis               -> simple derived metrics from captured orders
"""

from flask import Flask, jsonify, request
from flask_cors import CORS
import time
import base64
import re

app = Flask(__name__)
CORS(app)  # THIS ALLOWS ALL ORIGINS FOR DEMO

# INITIATE IN-MEMORY STORE (CLEARS ON PROCESS RESTART)
ORDERS = []
# SIMPLE AUTO-CORRECT ATRIFICIAL/SURROGATE ID
_order_counter = 0

# REQUIRED FIELDS
REQUIRED_FIELDS = [
    "first_name", "surname", "club_school",
    "contact_number", "contact_email",
    "payment_option", "costing"
]
# OPTIONAL FIELDS
OPTIONAL_FIELDS = [
    "colour", "colour_selection",
    "logo_image", "additional_notes"
]
# NUMBER AND EMAIL VALIDATION (SOUTH AFRICAN FORMAT)
PHONE_RE = re.compile(r'^(?:0|\+27)[1-9][0-9]{8}$', re.ASCII)
EMAIL_RE = re.compile(r'^[^@\s]+@[^@\s]+\.[^@\s]+$', re.ASCII)


def next_order_id() -> str:
    """Generate a simple incremental ID like PX01, PX02 (as a backup)."""
    global _order_counter
    _order_counter += 1
    return f"PX{_order_counter:02d}"


def validate_payload(payload: dict):
    """
    Basic validation process, checking:
      - if all required fields are present
      - Phone number in SA format
      - Email address in SA format
      - logo_image (if present) is plausibly base64 / data URL
    Returns (ok, errors:list[str])
    """
    errors = []

    # CHECKING REQUIRED FIELDS
    for f in REQUIRED_FIELDS:
        if not payload.get(f):
            errors.append(f"Missing required field: {f}")

    # CHECKING PHONE NUMBER
    phone = payload.get("contact_number", "")
    if phone and not PHONE_RE.match(phone):
        errors.append("Invalid contact_number format (expect 0XXXXXXXXX or +27XXXXXXXXX).")

    # CHECKING EMAIL ADDRESS
    email = payload.get("contact_email", "")
    if email and not EMAIL_RE.match(email):
        errors.append("Invalid contact_email format.")

    # CHECKING LOGO IMAGE (WHICH IS OPTIONAL)
    logo = payload.get("logo_image") or ""
    if logo:
        # ACCEPTS URLS & BASE64 DATA URLS
        if logo.startswith("data:"):
            if "," not in logo:
                errors.append("logo_image data URL malformed.")
        else:
            # CHECKING LIGHTWAY DECODABILITY OF BASE64
            try:
                # STRIPPING ANY PRESENT WHITESPACE
                base64.b64decode(logo.strip()[:200], validate=True)
            except Exception:
                errors.append("logo_image not valid base64 (first 200 chars failed).")

    return (len(errors) == 0, errors)

#----------------------------------------------------------------------------------------------
# ENDPOINT 1) LIST ALL ORDERS (GET  /api/orders)
#----------------------------------------------------------------------------------------------

@app.get("/api/orders")
def list_orders():
    """
    Returns all stored orders from html form submission on frontend
    """
    return jsonify({
        "status": "ok",
        "count": len(ORDERS),
        "orders": ORDERS
    }), 200

#----------------------------------------------------------------------------------------------
# ENDPOINT 2) CREATE NEW ORDER (POST /api/orders)
#----------------------------------------------------------------------------------------------

@app.post("/api/orders")
def create_order():
    """
    Accepts booking-form style JSON.
    Doesn't forward to Google Apps Script, simply a proxy capture for marking purposes.
    Stores order in memory.
    """
    if not request.is_json:
        return jsonify({"status": "error", "message": "Content-Type must be application/json"}), 415

    payload = request.get_json() or {}
    ok, errors = validate_payload(payload)
    if not ok:
        return jsonify({"status": "error", "errors": errors}), 400

    # NORMALISING COLOUR AS PREFERRING 'colour' OVER 'colour_selection'.
    colour = payload.get("colour") or payload.get("colour_selection") or ""

    provided_id = (
        payload.get("id")
        or payload.get("impression")
        or payload.get("impression_number")
    )
    if provided_id and any(o["id"] == provided_id for o in ORDERS):
        return jsonify({"status": "error", "message": f"ID {provided_id} already exists"}), 409

    order_id = provided_id if provided_id else next_order_id()
    ts = int(time.time())

    order_record = {
        "id": order_id,
        "timestamp": ts,
        "first_name": payload.get("first_name", "").strip(),
        "surname": payload.get("surname", "").strip(),
        "club_school": payload.get("club_school", "").strip(),
        "contact_number": payload.get("contact_number", "").strip(),
        "contact_email": payload.get("contact_email", "").strip(),
        "payment_option": payload.get("payment_option", "").strip(),
        "costing": payload.get("costing", "").strip(),
        "colour": colour.strip(),
        "additional_notes": payload.get("additional_notes", "").strip(),
        
        "logo_image_truncated": (payload.get("logo_image") or "")[:120] + ("…" if payload.get("logo_image") and len(payload.get("logo_image")) > 120 else "")
    }

    ORDERS.append(order_record)

    return jsonify({
        "status": "success",
        "id": order_id,
        "stored_fields": list(order_record.keys()),
        "message": "Order captured in proxy (not forwarded)."
    }), 201

#----------------------------------------------------------------------------------------------
# ENDPOINT 3) GET SINGLE ORDER (GET /api/orders/<order_id>)
#----------------------------------------------------------------------------------------------

@app.get("/api/orders/<order_id>")
def get_order(order_id):
    """
    Returns a single order using the <order_id> allocated from the Google Sheet upon appending a new order or 404.
    """
    for o in ORDERS:
        if o["id"] == order_id:
            return jsonify({"status": "ok", "order": o}), 200
    return jsonify({"status": "error", "message": f"Order {order_id} not found"}), 404

#----------------------------------------------------------------------------------------------
# ENDPOINT 4) UPDATE ORDER (PUT /api/orders/<order_id>)
#----------------------------------------------------------------------------------------------

@app.put("/api/orders/<order_id>")
def update_order(order_id):
    """
    Partial updats where providing any specific field response overwrites existing stored field value.
    Validation applied only to changed required fields to ensure response completeness; empty strings are allowed to clear optional fields such as additional_notes.
    """
    if not request.is_json:
        return jsonify({"status": "error", "message": "Content-Type must be application/json"}), 415

    payload = request.get_json() or {}
    for idx, o in enumerate(ORDERS):
        if o["id"] == order_id:
            # APPLIES CHANGES
            changed = {}
            for key in REQUIRED_FIELDS + OPTIONAL_FIELDS:
                if key in payload:
                    # COLOUR NORMALISATION
                    if key in ("colour", "colour_selection"):
                        new_colour = payload.get("colour") or payload.get("colour_selection") or ""
                        o["colour"] = new_colour.strip()
                        changed["colour"] = o["colour"]
                    elif key == "logo_image":
                        # TRUNCATING IMAGE FOR STORAGE AND DISPLAY
                        trunc = payload["logo_image"][:120] + ("…" if len(payload["logo_image"]) > 120 else "")
                        o["logo_image_truncated"] = trunc
                        changed["logo_image_truncated"] = trunc
                    else:
                        o[key] = (payload[key] or "").strip()
                        changed[key] = o[key]

            # VALIDATING REQUIRED FIELDS AFTER CHANGES
            ok, errors = validate_payload({
                **{f: o.get(f) for f in REQUIRED_FIELDS},
                "contact_number": o.get("contact_number"),
                "contact_email": o.get("contact_email"),
                "logo_image": payload.get("logo_image", "")
            })
            if not ok:
                return jsonify({"status": "error", "errors": errors}), 400

            ORDERS[idx] = o
            return jsonify({"status": "success", "id": order_id, "updated": changed}), 200

    return jsonify({"status": "error", "message": f"Order {order_id} not found"}), 404

#----------------------------------------------------------------------------------------------
# ENDPOINT 5) GET KPIS (GET /api/kpis)
#----------------------------------------------------------------------------------------------

@app.get("/api/kpis")
def get_kpis():
    """
    Simple derived metrics for demo (not tied to real sheet).
    """
    total = len(ORDERS)
    # KPI EXAMPLE: COUNT OF DISTINCT COSTING TYPES/UNIQUE PRODUCTS ORDERED
    costing_counts = {}
    for o in ORDERS:
        c = o.get("costing") or "Unknown"
        costing_counts[c] = costing_counts.get(c, 0) + 1
    # 4 KPIs: total orders, distinct product types ordered, breakdown per product type, most popular product
    return jsonify({
        "status": "ok",
        "total_orders": total,
        "distinct_product_types_ordered": len(costing_counts),
        "product_breakdown": costing_counts,
        "most_popular_product": max(costing_counts, key=costing_counts.get) if costing_counts else None
    }), 200

#----------------------------------------------------------------------------------------------
# ENDPOINT 6) SIMPLE HEALTH ENDPOINT OPTIONAL CHECK
#----------------------------------------------------------------------------------------------
@app.get("/health")
def health():
    return jsonify({"status": "ok", "orders_cached": len(ORDERS)}), 200


@app.get("/")
def root():
    return {"status": "ok", "message": "Proxy API running", "endpoints": [
        "/api/orders", "/api/orders/<id>", "/api/kpis"
    ]}


if __name__ == "__main__":
    # debug = True for local development (disable in deployment).
    app.run(host="0.0.0.0", port=5000, debug=True)
